"""Seed data and assumptions for the analytics engine."""

DEFAULT_PROFILE = {
    "name": "Aarav Mehta",
    "age": 29,
    "employment_status": "Salaried",
    "location": "Bengaluru, India",
    "dependents": 2,
    "monthly_income": 120000,
    "monthly_expenses": {
        "rent": 28000,
        "food": 12000,
        "electricity": 3500,
        "transportation": 8000,
        "education": 0,
        "healthcare": 5000,
        "insurance": 4500,
        "emis": 10000,
        "subscriptions": 1200,
        "entertainment": 6000,
        "other_essential": 6500,
    },
    "existing_savings": 220000,
    "bank_balance": 150000,
    "emergency_fund": 95000,
    "loans": 420000,
    "credit_card_obligations": 18000,
    "current_portfolio_value": 720000,
    "monthly_investment_capacity_target": 30000,
    "risk_inputs": {
        "investment_horizon_years": 12,
        "loss_tolerance": 18,
        "volatility_comfort": 7,
        "income_stability": 8,
        "market_knowledge": 6,
    },
    "goals": [
        {
            "name": "Emergency Fund",
            "target_amount": 270000,
            "current_amount": 95000,
            "years": 1,
            "priority": "High",
        },
        {
            "name": "House Down Payment",
            "target_amount": 2500000,
            "current_amount": 300000,
            "years": 8,
            "priority": "High",
        },
        {
            "name": "Retirement",
            "target_amount": 30000000,
            "current_amount": 220000,
            "years": 31,
            "priority": "High",
        },
        {
            "name": "Travel Fund",
            "target_amount": 300000,
            "current_amount": 40000,
            "years": 3,
            "priority": "Medium",
        },
    ],
    "portfolio": [
        {
            "asset": "Large Cap Index Fund",
            "category": "Equity",
            "sector": "Diversified",
            "amount": 210000,
            "return_pct": 16.4,
            "volatility_pct": 15.0,
            "liquidity_score": 9,
        },
        {
            "asset": "Flexi Cap Mutual Fund",
            "category": "Mutual Funds",
            "sector": "Diversified",
            "amount": 180000,
            "return_pct": 14.1,
            "volatility_pct": 17.0,
            "liquidity_score": 8,
        },
        {
            "asset": "Tax Saver ELSS",
            "category": "Mutual Funds",
            "sector": "Diversified",
            "amount": 90000,
            "return_pct": 13.2,
            "volatility_pct": 18.0,
            "liquidity_score": 5,
        },
        {
            "asset": "Corporate Bond Fund",
            "category": "Debt",
            "sector": "Fixed Income",
            "amount": 110000,
            "return_pct": 7.2,
            "volatility_pct": 4.5,
            "liquidity_score": 8,
        },
        {
            "asset": "Fixed Deposit",
            "category": "Debt",
            "sector": "Fixed Income",
            "amount": 65000,
            "return_pct": 6.8,
            "volatility_pct": 1.2,
            "liquidity_score": 6,
        },
        {
            "asset": "Gold ETF",
            "category": "Gold",
            "sector": "Commodity",
            "amount": 45000,
            "return_pct": 10.6,
            "volatility_pct": 11.0,
            "liquidity_score": 8,
        },
        {
            "asset": "US Index ETF",
            "category": "International",
            "sector": "Technology",
            "amount": 20000,
            "return_pct": 12.5,
            "volatility_pct": 19.5,
            "liquidity_score": 7,
        },
    ],
}

MARKET_SNAPSHOT = {
    "timestamp": "2026-08-23T09:15:00+05:30",
    "indices": [
        {"name": "Nifty 50", "value": 25462.3, "change_pct": 0.84},
        {"name": "Sensex", "value": 83618.7, "change_pct": 0.76},
        {"name": "Nifty Midcap 150", "value": 20543.2, "change_pct": 1.12},
        {"name": "S&P 500", "value": 6741.8, "change_pct": 0.21},
        {"name": "NASDAQ 100", "value": 23918.1, "change_pct": 0.35},
    ],
    "macro": [
        {"label": "India CPI", "value": "4.8%", "signal": "stable"},
        {"label": "RBI Repo Rate", "value": "6.25%", "signal": "neutral"},
        {"label": "10Y G-Sec Yield", "value": "7.03%", "signal": "watch"},
        {"label": "USD/INR", "value": "83.14", "signal": "stable"},
        {"label": "Gold (10g)", "value": "₹74,850", "signal": "positive"},
    ],
    "sectors": [
        {"name": "Banking", "return_pct": 13.1, "volatility_pct": 14.5, "momentum": "Strong"},
        {"name": "Information Technology", "return_pct": 10.4, "volatility_pct": 18.2, "momentum": "Improving"},
        {"name": "Healthcare", "return_pct": 8.6, "volatility_pct": 11.9, "momentum": "Defensive"},
        {"name": "FMCG", "return_pct": 7.4, "volatility_pct": 9.6, "momentum": "Stable"},
        {"name": "Energy", "return_pct": 11.2, "volatility_pct": 16.8, "momentum": "Cyclical"},
        {"name": "Automobile", "return_pct": 14.8, "volatility_pct": 17.1, "momentum": "Strong"},
        {"name": "Renewable Energy", "return_pct": 16.0, "volatility_pct": 21.4, "momentum": "High Growth"},
    ],
}

ASSET_ASSUMPTIONS = {
    "Conservative": {
        "expected_return": 0.082,
        "volatility": 0.09,
        "allocation": {
            "Equity": 25,
            "Debt": 40,
            "Gold": 10,
            "International": 5,
            "Cash": 20,
        },
    },
    "Moderate": {
        "expected_return": 0.115,
        "volatility": 0.14,
        "allocation": {
            "Equity": 50,
            "Debt": 25,
            "Gold": 10,
            "International": 5,
            "Cash": 10,
        },
    },
    "Aggressive": {
        "expected_return": 0.142,
        "volatility": 0.19,
        "allocation": {
            "Equity": 65,
            "Debt": 15,
            "Gold": 8,
            "International": 7,
            "Cash": 5,
        },
    },
}

